language: node_js
node_js: 12.18.3
services: docker

stages:
  - publish

branches:
  only:
    - master

jobs:
  include:
    # Build and publish latest tag
    - stage: publish
      before_script:
        - docker build -t westegg .
        - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USER" --password-stdin
      script:
        # Latest tag
        - docker tag westegg gatsbytv/westegg:latest
        - docker push gatsbytv/westegg:latest

    # TODO: Deploy docker release tag
    # - stage: deploy
    #   script:
    #     # Release tag
    #     - docker tag westegg gatsbytv/westegg:$TRAVIS_TAG
    #     - docker push westegg gatsbytv/westegg:$TRAVIS_TAG
    #   on:
    #     tags: true
