language: node_js
node_js: 12.18.3
services: docker

stages:
  - build
  - publish

jobs:
  include:
    # Check prettier linting and build typescript
    - stage: build
      script:
        - npm run format:check
        - npm run build
    # Build and publish docker tags
    - stage: publish
      if: branch = master
      before_script:
        - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USER" --password-stdin
      script:
        # Build dockerfile
        - make build
        # Push tags
        - make push
