language: node_js
node_js: 12.18.3
services: docker

stages:
  - build
  - publish

# branches:
#   only:
#     - master

jobs:
  include:
    # Check prettier linting and build typescript
    - stage: build
      script:
        - npm run format:check
        - npm run build
    # Build and publish latest tag
    - stage: publish
      if: branch = master
      before_script:
        - docker build -t westegg .
        - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USER" --password-stdin
      script:
        # Latest tag
        - docker tag westegg gatsbytv/westegg:latest
        # Versioned tag
        - export APP_NAME=`grep '"name":' package.json | cut -d '"' -f4`
        - export APP_VERSION=`grep '"version":' package.json | cut -d '"' -f4`
        - export BUILD=`git rev-parse --short HEAD`
        - docker tag westegg gatsbytv/$(APP_NAME):$(APP_VERSION)-$(BUILD)
        # Push tags
        - docker push gatsbytv/westegg:latest gatsbytv/$(APP_NAME):$(APP_VERSION)-$(BUILD)
