version: "3"
services:

  # NodeJS API server
  api:
    build: .
    image: api
    environment:
      # API app config
      PORT: 3001
      # Mongo config
      MONGO_HOST: mongo
      MONGO_PORT: 27017
      MONGO_API_USER: gatsby
      MONGO_API_PASS: ${MONGO_API_PASS}
      MONGO_API_DB: gatsby
      # Misc config
      JWT_SECRET: ${JWT_SECRET}
      # LOGGING_LEVEL: ${LOGGING_LEVEL}
    restart: always
    networks:
      - webnet

  # Mongo
  mongo:
    image: mongo:4.4.1
    environment:
      # Root db user
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_ROOT_PASS}
      # API db and user
      - MONGO_INITDB_DATABASE=gatsby
      - MONGO_API_USER=gatsby
      - MONGO_API_PASS=${MONGO_API_PASS}
    volumes:
      - ./.db:/data/db
      - ./mongo/init.sh:/docker-entrypoint-initdb.d/mongo-init.sh:ro
    ports:
      - 27017:27017
    networks:
      - webnet

networks:
  webnet:
