version: "3"
services:

  # NodeJS API server
  api:
    build: .
    image: api
    environment:
      # API app config
      PORT: 3001
      # Mongo config
      MONGO_HOST: mongo
      MONGO_PORT: 27017
      MONGO_API_USER: gatsby
      MONGO_API_PASS: ${MONGO_API_PASS}
      MONGO_API_DB: gatsby
      # Misc config
      JWT_SECRET: ${JWT_SECRET}
      ENVIRONMENT: ${ENVIRONMENT}
    ports:
     - 3001:3001
    restart: always
    networks:
      - westegg

  # TODO: Redis

  # Mongo
  mongo:
    image: mongo:4.4.1
    environment:
      # Root db user
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_ROOT_PASS}
      # API db and user
      - MONGO_INITDB_DATABASE=gatsby
      - MONGO_API_USER=gatsby
      - MONGO_API_PASS=${MONGO_API_PASS}
    volumes:
      - ./.db:/data/db
      - ./mongo/init.sh:/docker-entrypoint-initdb.d/mongo-init.sh:ro
    ports:
      - 27017:27017
    networks:
      - westegg

  # IPFS
  ipfs:
    # TODO: Decide on stable ipfs version to use in prod
    image: ipfs/go-ipfs:bifrost-latest
    volumes:
      - ./.ipfs:/data/ipfs
    ports:
      # Swarm TCP
      - 4001:4001
      # Swarm Websockets
      - 8081:8081
      # HTTP Gateway
      - 8080:8080
      # Daemon API -- DO NOT EXPOSE PUBLICLY
      - 127.0.0.1:5001:5001
    networks:
      - westegg

networks:
  westegg:
